site_name: RGB Composite Recipes for Meteorological Imagers
theme:
  name: material

nav:
  - Home: index.md
  - Recipes:
    - Day Cloud Phase RGB: cloud-phase.md
    - Day Cloud Type RGB: cloud-type.md
    - 24-hour Microphysics Dust RGB: dust.md
    - Day Severe Storms RGB: severe-convection.md

markdown_extensions:
  - tables
  - attr_list
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
